replicaCount: 1

image:
  repository: jessynt/sensor-pipe
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
extraEnv: {}
service:
  type: ClusterIP
  port: 80

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
