version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test
workflows:
  version: 2
  test:
    jobs:
      - test